### ISSUE TITLE
FE As a user, I should be able to add journal entries and see past entries.

### ISSUE THREAD

**Issue by nzambonivergara** [bullet-capstone/glow-up-fe#3]
Acceptance Criteria

Scenario: As a user, when I arrive at the Journal page:
 - I should see a text area to allow me enter and submit new journal 
 - I should see a section below the text area displaying my previous entries
 - Given that I have previous journal entries, I see my previous entries
 - If I don't have previous entries, I see a message indicating no previous entries.
-  After I submit new journal entry, I should see my new entry in previous entries.

**Comment by woaishenzhen** [comment]
Comprehensive user stories Natalia! Great work! I changed one typo, added two details to mood selection and habit selection and re-org the journal stories. I think we are good to go.
